### ISSUE TITLE
`spawn': No such file or directory - bundle outdated (Errno::ENOENT)

### ISSUE THREAD

**Issue by yegor256** [lpender/bummr#44]
I'm trying to run `bummr update`:

```
Bundle complete! 17 Gemfile dependencies, 67 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
/Users/yegor/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - bundle outdated (Errno::ENOENT)
	from /Users/yegor/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /Users/yegor/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:147:in `popen2'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/bummr-0.1.8/lib/bummr/outdated.rb:14:in `outdated_gems'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/bummr-0.1.8/lib/bummr/cli.rb:23:in `update'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/bummr-0.1.8/bin/bummr:4:in `<top (required)>'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/bin/bummr:22:in `load'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/bin/bummr:22:in `<main>'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

@lpender can you help?

**Comment by lpender** [comment]
What does `gem -v bundler` return?

**Comment by rmaspero** [comment]
I get the same issue. `gem -v bundler` returns 2.6.8

**Comment by lpender** [comment]
I can't seem to reproduce. 

Does 

```
bundle outdated
```

return anything on your system?

-----

If you try:

```
gem install bummr -v 0.1.7
```

or

```
gem install bummr -v 0.1.6
```

Do either of those work?

**Comment by rmaspero** [comment]
`bundle outdated`

returns

```
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...

Outdated gems included in the bundle:
  * actioncable (newest 5.1.2, installed 5.1.1)
  * actionmailer (newest 5.1.2, installed 5.1.1)
  * actionpack (newest 5.1.2, installed 5.1.1)
  * actionview (newest 5.1.2, installed 5.1.1)
  * activejob (newest 5.1.2, installed 5.1.1)
  * activemodel (newest 5.1.2, installed 5.1.1)
  * activerecord (newest 5.1.2, installed 5.1.1)
  * activesupport (newest 5.1.2, installed 5.1.1)
  * brakeman (newest 3.7.0, installed 3.6.1) in groups "development"
  * bullet (newest 5.6.0, installed 5.5.1) in groups "development"
  * capybara (newest 2.14.4, installed 2.14.0) in groups "development, test"
  * coffee-rails (newest 4.2.2, installed 4.2.1, requested ~> 4.2) in groups "default"
  * email_spec (newest 2.1.1, installed 2.1.0) in groups "development, test"
  * erubi (newest 1.6.1, installed 1.6.0)
  * i18n (newest 0.8.6, installed 0.8.1)
  * jbuilder (newest 2.7.0, installed 2.6.4, requested ~> 2.5) in groups "default"
  * listen (newest 3.1.5, installed 3.0.8, requested ~> 3.0.5) in groups "development"
  * mail (newest 2.6.6, installed 2.6.5)
  * mini_portile2 (newest 2.2.0, installed 2.1.0)
  * nio4r (newest 2.1.0, installed 2.0.0)
  * nokogiri (newest 1.8.0, installed 1.7.2)
  * pg (newest 0.21.0, installed 0.20.0, requested ~> 0.18) in groups "default"
  * puma (newest 3.9.1, installed 3.8.2, requested ~> 3.0) in groups "default"
  * rack-test (newest 0.7.0, installed 0.6.3)
  * rails (newest 5.1.2, installed 5.1.1, requested ~> 5.1.1) in groups "default"
  * railties (newest 5.1.2, installed 5.1.1)
  * rb-fsevent (newest 0.10.2, installed 0.9.8)
  * rb-inotify (newest 0.9.10, installed 0.9.8)
  * sass (newest 3.5.1, installed 3.4.23)
  * shoulda-matchers (newest 3.1.2, installed 3.1.1, requested ~> 3.1) in groups "development, test"
  * slop (newest 4.5.0, installed 3.6.0)
  * spring (newest 2.0.2, installed 2.0.1) in groups "development"
  * xpath (newest 2.1.0, installed 2.0.0)
```

Both of the gem installs seem to work fine however I still get the same error when running `bummr update`

Only thing I can see is that @yegor256 is using RVM and I am using RBENV to manage our Ruby versions, I'm using Ruby 2.4.0.

**Comment by lpender** [comment]
Strange.

The error is coming [from this line](https://github.com/lpender/bummr/blob/69d013da719ef0350bf4babc109fce5173bd6c00/lib/bummr/outdated.rb#L14) and seems to indicate that when we send the command `bundle outdated` to the command line, it's returning "No file or directory".

I'm wondering if there's something going on with the `PATH`...

**Comment by rmaspero** [comment]
The path it errors on for me is 
`/Users/rupertmaspero/.rbenv/versions/2.4.0/lib/ruby/2.4.0/`
which 100% exists.

I do have `eval "$(rbenv init -)"` in my bash file so when I do `echo $PATH` I get 
`/Users/rupertmaspero/.rbenv/shims:/Users/rupertmaspero/.rbenv/shims:/Users/rupertmaspero/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

This is because rbenv is installed with Hombrew (https://github.com/rbenv/rbenv#homebrew-on-mac-os-x)

**Comment by diegorv** [comment]
Same here with rbenv..

```
/Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - bundle outdated (Errno::ENOENT)
	from /Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
	from /Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open3.rb:147:in `popen2'
	from /Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bummr-0.1.8/lib/bummr/outdated.rb:14:in `outdated_gems'
	from /Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bummr-0.1.8/lib/bummr/cli.rb:23:in `update'
	from /Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/diegorv/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bummr-0.1.8/bin/bummr:4:in `<top (required)>'
	from /Users/diegorv/.rbenv/versions/2.4.1/bin/bummr:22:in `load'
	from /Users/diegorv/.rbenv/versions/2.4.1/bin/bummr:22:in `<main>'
```

```
gem -v bundler                                                                                                                                                                                                                                         
2.6.11
```

```
echo $PATH                                                                                                                                                                                                                                             
/Users/diegorv/.rbenv/shims:/Users/diegorv/local:/usr/local/opt/qt@5.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/opt/fzf/bin
```

```
which bundler                                                                                                                                                                                                                                          
/Users/diegorv/.rbenv/shims/bundler
```

**Comment by lpender** [comment]
Solved. `gem install bummr` or `gem install bummr@0.2.1`.

Thanks for the bug reports!
